// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type DispatchedTask struct {
	ExecutionID      pgtype.UUID        `json:"execution_id"`
	NodeID           string             `json:"node_id"`
	DispatchID       pgtype.UUID        `json:"dispatch_id"`
	DispatchedAt     pgtype.Timestamptz `json:"dispatched_at"`
	AttemptTimeoutAt pgtype.Timestamptz `json:"attempt_timeout_at"`
}

type NodeExecution struct {
	ExecutionID  pgtype.UUID        `json:"execution_id"`
	NodeID       string             `json:"node_id"`
	Status       string             `json:"status"`
	AttemptCount int32              `json:"attempt_count"`
	MaxAttempts  int32              `json:"max_attempts"`
	InputData    []byte             `json:"input_data"`
	OutputData   []byte             `json:"output_data"`
	ErrorMessage pgtype.Text        `json:"error_message"`
	StartedAt    pgtype.Timestamptz `json:"started_at"`
	CompletedAt  pgtype.Timestamptz `json:"completed_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type OutboxMessage struct {
	ID          int64              `json:"id"`
	Queue       string             `json:"queue"`
	Payload     []byte             `json:"payload"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	PublishedAt pgtype.Timestamptz `json:"published_at"`
}

type WorkflowRun struct {
	ExecutionID     pgtype.UUID        `json:"execution_id"`
	WorkflowID      pgtype.UUID        `json:"workflow_id"`
	WorkflowVersion int32              `json:"workflow_version"`
	DagDefinition   []byte             `json:"dag_definition"`
	Status          string             `json:"status"`
	StartedAt       pgtype.Timestamptz `json:"started_at"`
	CompletedAt     pgtype.Timestamptz `json:"completed_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	TriggerData     []byte             `json:"trigger_data"`
}
