// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteDispatchedTask = `-- name: DeleteDispatchedTask :exec
DELETE FROM dispatched_tasks
WHERE execution_id = $1 AND node_id = $2
`

type DeleteDispatchedTaskParams struct {
	ExecutionID pgtype.UUID `json:"execution_id"`
	NodeID      string      `json:"node_id"`
}

func (q *Queries) DeleteDispatchedTask(ctx context.Context, arg DeleteDispatchedTaskParams) error {
	_, err := q.db.Exec(ctx, deleteDispatchedTask, arg.ExecutionID, arg.NodeID)
	return err
}

const getDispatchedTask = `-- name: GetDispatchedTask :one
SELECT execution_id, node_id, dispatch_id, dispatched_at, attempt_timeout_at FROM dispatched_tasks
WHERE execution_id = $1 AND node_id = $2
`

type GetDispatchedTaskParams struct {
	ExecutionID pgtype.UUID `json:"execution_id"`
	NodeID      string      `json:"node_id"`
}

func (q *Queries) GetDispatchedTask(ctx context.Context, arg GetDispatchedTaskParams) (DispatchedTask, error) {
	row := q.db.QueryRow(ctx, getDispatchedTask, arg.ExecutionID, arg.NodeID)
	var i DispatchedTask
	err := row.Scan(
		&i.ExecutionID,
		&i.NodeID,
		&i.DispatchID,
		&i.DispatchedAt,
		&i.AttemptTimeoutAt,
	)
	return i, err
}

const getNodeExecution = `-- name: GetNodeExecution :one
SELECT execution_id, node_id, status, attempt_count, max_attempts, input_data, output_data, error_message, started_at, completed_at, updated_at FROM node_executions
WHERE execution_id = $1 AND node_id = $2
`

type GetNodeExecutionParams struct {
	ExecutionID pgtype.UUID `json:"execution_id"`
	NodeID      string      `json:"node_id"`
}

func (q *Queries) GetNodeExecution(ctx context.Context, arg GetNodeExecutionParams) (NodeExecution, error) {
	row := q.db.QueryRow(ctx, getNodeExecution, arg.ExecutionID, arg.NodeID)
	var i NodeExecution
	err := row.Scan(
		&i.ExecutionID,
		&i.NodeID,
		&i.Status,
		&i.AttemptCount,
		&i.MaxAttempts,
		&i.InputData,
		&i.OutputData,
		&i.ErrorMessage,
		&i.StartedAt,
		&i.CompletedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkflowRun = `-- name: GetWorkflowRun :one
SELECT execution_id, workflow_id, workflow_version, dag_definition, status, started_at, completed_at, updated_at FROM workflow_runs
WHERE execution_id = $1 FOR UPDATE
`

func (q *Queries) GetWorkflowRun(ctx context.Context, executionID pgtype.UUID) (WorkflowRun, error) {
	row := q.db.QueryRow(ctx, getWorkflowRun, executionID)
	var i WorkflowRun
	err := row.Scan(
		&i.ExecutionID,
		&i.WorkflowID,
		&i.WorkflowVersion,
		&i.DagDefinition,
		&i.Status,
		&i.StartedAt,
		&i.CompletedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertDispatchedTask = `-- name: InsertDispatchedTask :one
INSERT INTO dispatched_tasks (
    execution_id, node_id, attempt_timeout_at
) VALUES (
    $1, $2, $3
) RETURNING dispatch_id
`

type InsertDispatchedTaskParams struct {
	ExecutionID      pgtype.UUID        `json:"execution_id"`
	NodeID           string             `json:"node_id"`
	AttemptTimeoutAt pgtype.Timestamptz `json:"attempt_timeout_at"`
}

func (q *Queries) InsertDispatchedTask(ctx context.Context, arg InsertDispatchedTaskParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, insertDispatchedTask, arg.ExecutionID, arg.NodeID, arg.AttemptTimeoutAt)
	var dispatch_id pgtype.UUID
	err := row.Scan(&dispatch_id)
	return dispatch_id, err
}

const insertNodeExecution = `-- name: InsertNodeExecution :exec
INSERT INTO node_executions (
    execution_id, node_id, status, max_attempts
) VALUES (
    $1, $2, $3, $4
) ON CONFLICT (execution_id, node_id) DO NOTHING
`

type InsertNodeExecutionParams struct {
	ExecutionID pgtype.UUID `json:"execution_id"`
	NodeID      string      `json:"node_id"`
	Status      string      `json:"status"`
	MaxAttempts int32       `json:"max_attempts"`
}

func (q *Queries) InsertNodeExecution(ctx context.Context, arg InsertNodeExecutionParams) error {
	_, err := q.db.Exec(ctx, insertNodeExecution,
		arg.ExecutionID,
		arg.NodeID,
		arg.Status,
		arg.MaxAttempts,
	)
	return err
}

const insertWorkflowRun = `-- name: InsertWorkflowRun :exec
INSERT INTO workflow_runs (
    execution_id, workflow_id, workflow_version, dag_definition, status, started_at
) VALUES (
    $1, $2, $3, $4, $5, $6
) ON CONFLICT (execution_id) DO NOTHING
`

type InsertWorkflowRunParams struct {
	ExecutionID     pgtype.UUID        `json:"execution_id"`
	WorkflowID      pgtype.UUID        `json:"workflow_id"`
	WorkflowVersion int32              `json:"workflow_version"`
	DagDefinition   []byte             `json:"dag_definition"`
	Status          string             `json:"status"`
	StartedAt       pgtype.Timestamptz `json:"started_at"`
}

func (q *Queries) InsertWorkflowRun(ctx context.Context, arg InsertWorkflowRunParams) error {
	_, err := q.db.Exec(ctx, insertWorkflowRun,
		arg.ExecutionID,
		arg.WorkflowID,
		arg.WorkflowVersion,
		arg.DagDefinition,
		arg.Status,
		arg.StartedAt,
	)
	return err
}

const listAllNodeExecutions = `-- name: ListAllNodeExecutions :many
SELECT execution_id, node_id, status, attempt_count, max_attempts, input_data, output_data, error_message, started_at, completed_at, updated_at FROM node_executions
WHERE execution_id = $1
`

func (q *Queries) ListAllNodeExecutions(ctx context.Context, executionID pgtype.UUID) ([]NodeExecution, error) {
	rows, err := q.db.Query(ctx, listAllNodeExecutions, executionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NodeExecution
	for rows.Next() {
		var i NodeExecution
		if err := rows.Scan(
			&i.ExecutionID,
			&i.NodeID,
			&i.Status,
			&i.AttemptCount,
			&i.MaxAttempts,
			&i.InputData,
			&i.OutputData,
			&i.ErrorMessage,
			&i.StartedAt,
			&i.CompletedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCompletedNodeExecutions = `-- name: ListCompletedNodeExecutions :many
SELECT execution_id, node_id, status, attempt_count, max_attempts, input_data, output_data, error_message, started_at, completed_at, updated_at FROM node_executions
WHERE execution_id = $1 AND status IN ('SUCCESS', 'SKIPPED')
`

func (q *Queries) ListCompletedNodeExecutions(ctx context.Context, executionID pgtype.UUID) ([]NodeExecution, error) {
	rows, err := q.db.Query(ctx, listCompletedNodeExecutions, executionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NodeExecution
	for rows.Next() {
		var i NodeExecution
		if err := rows.Scan(
			&i.ExecutionID,
			&i.NodeID,
			&i.Status,
			&i.AttemptCount,
			&i.MaxAttempts,
			&i.InputData,
			&i.OutputData,
			&i.ErrorMessage,
			&i.StartedAt,
			&i.CompletedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateNodeExecutionStatus = `-- name: UpdateNodeExecutionStatus :exec
UPDATE node_executions
SET status = $3, output_data = $4, error_message = $5, updated_at = now(), completed_at = $6
WHERE execution_id = $1 AND node_id = $2 AND status IN ('QUEUED', 'RUNNING')
`

type UpdateNodeExecutionStatusParams struct {
	ExecutionID  pgtype.UUID        `json:"execution_id"`
	NodeID       string             `json:"node_id"`
	Status       string             `json:"status"`
	OutputData   []byte             `json:"output_data"`
	ErrorMessage pgtype.Text        `json:"error_message"`
	CompletedAt  pgtype.Timestamptz `json:"completed_at"`
}

func (q *Queries) UpdateNodeExecutionStatus(ctx context.Context, arg UpdateNodeExecutionStatusParams) error {
	_, err := q.db.Exec(ctx, updateNodeExecutionStatus,
		arg.ExecutionID,
		arg.NodeID,
		arg.Status,
		arg.OutputData,
		arg.ErrorMessage,
		arg.CompletedAt,
	)
	return err
}

const updateWorkflowRunStatus = `-- name: UpdateWorkflowRunStatus :exec
UPDATE workflow_runs
SET status = $2, updated_at = now(), completed_at = $3
WHERE execution_id = $1
`

type UpdateWorkflowRunStatusParams struct {
	ExecutionID pgtype.UUID        `json:"execution_id"`
	Status      string             `json:"status"`
	CompletedAt pgtype.Timestamptz `json:"completed_at"`
}

func (q *Queries) UpdateWorkflowRunStatus(ctx context.Context, arg UpdateWorkflowRunStatusParams) error {
	_, err := q.db.Exec(ctx, updateWorkflowRunStatus, arg.ExecutionID, arg.Status, arg.CompletedAt)
	return err
}

const insertOutboxMessage = `-- name: InsertOutboxMessage :exec
INSERT INTO outbox_messages (queue, payload)
VALUES ($1, $2)
`

type InsertOutboxMessageParams struct {
	Queue   string `json:"queue"`
	Payload []byte `json:"payload"`
}

func (q *Queries) InsertOutboxMessage(ctx context.Context, arg InsertOutboxMessageParams) error {
	_, err := q.db.Exec(ctx, insertOutboxMessage, arg.Queue, arg.Payload)
	return err
}

const claimUnpublishedMessages = `-- name: ClaimUnpublishedMessages :many
SELECT id, queue, payload, created_at, published_at FROM outbox_messages
WHERE published_at IS NULL
ORDER BY created_at ASC
LIMIT $1
FOR UPDATE SKIP LOCKED
`

func (q *Queries) ClaimUnpublishedMessages(ctx context.Context, limit int32) ([]OutboxMessage, error) {
	rows, err := q.db.Query(ctx, claimUnpublishedMessages, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OutboxMessage
	for rows.Next() {
		var i OutboxMessage
		if err := rows.Scan(
			&i.ID,
			&i.Queue,
			&i.Payload,
			&i.CreatedAt,
			&i.PublishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markOutboxMessagePublished = `-- name: MarkOutboxMessagePublished :exec
UPDATE outbox_messages
SET published_at = now()
WHERE id = $1
`

func (q *Queries) MarkOutboxMessagePublished(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markOutboxMessagePublished, id)
	return err
}
