// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Execution struct {
	ID              pgtype.UUID
	WorkflowID      pgtype.UUID
	WorkflowVersion int32
	IdempotencyKey  string
	Status          string
	StartedAt       pgtype.Timestamptz
	CompletedAt     pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type Schedule struct {
	ID             pgtype.UUID
	WorkflowID     pgtype.UUID
	CronExpression string
	NextRunAt      pgtype.Timestamptz
	LeasedBy       pgtype.Text
	LeaseExpiresAt pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
}

type Webhook struct {
	ID         pgtype.UUID
	WorkflowID pgtype.UUID
	Path       string
	Secret     string
	CreatedAt  pgtype.Timestamptz
}

type WebhookIdempotency struct {
	WebhookID      pgtype.UUID
	IdempotencyKey string
	ExecutionID    pgtype.UUID
	CreatedAt      pgtype.Timestamptz
	ExpiresAt      pgtype.Timestamptz
}

type Workflow struct {
	ID              pgtype.UUID
	Name            string
	CreatedAt       pgtype.Timestamptz
	Fingerprint     pgtype.Text
	TemplateID      pgtype.Text
	TemplateVersion pgtype.Int4
}

type WorkflowVersion struct {
	WorkflowID    pgtype.UUID
	Version       int32
	DagDefinition []byte
	CreatedAt     pgtype.Timestamptz
}
