// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimDueSchedules = `-- name: ClaimDueSchedules :many
UPDATE schedules
SET leased_by = $1, lease_expires_at = $2
WHERE id IN (
    SELECT s.id FROM schedules s
    WHERE s.next_run_at <= $3 AND (s.leased_by IS NULL OR s.lease_expires_at < $3)
    FOR UPDATE SKIP LOCKED
    LIMIT $4
)
RETURNING id, workflow_id, cron_expression, next_run_at, leased_by, lease_expires_at, created_at
`

type ClaimDueSchedulesParams struct {
	LeasedBy       pgtype.Text
	LeaseExpiresAt pgtype.Timestamptz
	NextRunAt      pgtype.Timestamptz
	Limit          int32
}

func (q *Queries) ClaimDueSchedules(ctx context.Context, arg ClaimDueSchedulesParams) ([]Schedule, error) {
	rows, err := q.db.Query(ctx, claimDueSchedules,
		arg.LeasedBy,
		arg.LeaseExpiresAt,
		arg.NextRunAt,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Schedule
	for rows.Next() {
		var i Schedule
		if err := rows.Scan(
			&i.ID,
			&i.WorkflowID,
			&i.CronExpression,
			&i.NextRunAt,
			&i.LeasedBy,
			&i.LeaseExpiresAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createExecution = `-- name: CreateExecution :one
INSERT INTO executions (workflow_id, workflow_version, idempotency_key, status)
VALUES ($1, $2, $3, $4)
ON CONFLICT (workflow_id, idempotency_key) DO NOTHING
RETURNING id, workflow_id, workflow_version, idempotency_key, status, started_at, completed_at, created_at, updated_at
`

type CreateExecutionParams struct {
	WorkflowID      pgtype.UUID
	WorkflowVersion int32
	IdempotencyKey  string
	Status          string
}

func (q *Queries) CreateExecution(ctx context.Context, arg CreateExecutionParams) (Execution, error) {
	row := q.db.QueryRow(ctx, createExecution,
		arg.WorkflowID,
		arg.WorkflowVersion,
		arg.IdempotencyKey,
		arg.Status,
	)
	var i Execution
	err := row.Scan(
		&i.ID,
		&i.WorkflowID,
		&i.WorkflowVersion,
		&i.IdempotencyKey,
		&i.Status,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSchedule = `-- name: CreateSchedule :one
INSERT INTO schedules (workflow_id, cron_expression, next_run_at)
VALUES ($1, $2, $3)
RETURNING id, workflow_id, cron_expression, next_run_at, created_at
`

type CreateScheduleParams struct {
	WorkflowID     pgtype.UUID
	CronExpression string
	NextRunAt      pgtype.Timestamptz
}

type CreateScheduleRow struct {
	ID             pgtype.UUID
	WorkflowID     pgtype.UUID
	CronExpression string
	NextRunAt      pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
}

func (q *Queries) CreateSchedule(ctx context.Context, arg CreateScheduleParams) (CreateScheduleRow, error) {
	row := q.db.QueryRow(ctx, createSchedule, arg.WorkflowID, arg.CronExpression, arg.NextRunAt)
	var i CreateScheduleRow
	err := row.Scan(
		&i.ID,
		&i.WorkflowID,
		&i.CronExpression,
		&i.NextRunAt,
		&i.CreatedAt,
	)
	return i, err
}

const createWebhook = `-- name: CreateWebhook :one
INSERT INTO webhooks (workflow_id, path, secret)
VALUES ($1, $2, $3)
RETURNING id, workflow_id, path, secret, created_at
`

type CreateWebhookParams struct {
	WorkflowID pgtype.UUID
	Path       string
	Secret     string
}

func (q *Queries) CreateWebhook(ctx context.Context, arg CreateWebhookParams) (Webhook, error) {
	row := q.db.QueryRow(ctx, createWebhook, arg.WorkflowID, arg.Path, arg.Secret)
	var i Webhook
	err := row.Scan(
		&i.ID,
		&i.WorkflowID,
		&i.Path,
		&i.Secret,
		&i.CreatedAt,
	)
	return i, err
}

const createWorkflow = `-- name: CreateWorkflow :one
INSERT INTO workflows (name)
VALUES ($1)
RETURNING id, name, created_at
`

func (q *Queries) CreateWorkflow(ctx context.Context, name string) (Workflow, error) {
	row := q.db.QueryRow(ctx, createWorkflow, name)
	var i Workflow
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const createWorkflowVersion = `-- name: CreateWorkflowVersion :one
INSERT INTO workflow_versions (workflow_id, version, dag_definition)
VALUES ($1, $2, $3)
RETURNING workflow_id, version, dag_definition, created_at
`

type CreateWorkflowVersionParams struct {
	WorkflowID    pgtype.UUID
	Version       int32
	DagDefinition []byte
}

func (q *Queries) CreateWorkflowVersion(ctx context.Context, arg CreateWorkflowVersionParams) (WorkflowVersion, error) {
	row := q.db.QueryRow(ctx, createWorkflowVersion, arg.WorkflowID, arg.Version, arg.DagDefinition)
	var i WorkflowVersion
	err := row.Scan(
		&i.WorkflowID,
		&i.Version,
		&i.DagDefinition,
		&i.CreatedAt,
	)
	return i, err
}

const getExecution = `-- name: GetExecution :one
SELECT id, workflow_id, workflow_version, idempotency_key, status, started_at, completed_at, created_at, updated_at FROM executions
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetExecution(ctx context.Context, id pgtype.UUID) (Execution, error) {
	row := q.db.QueryRow(ctx, getExecution, id)
	var i Execution
	err := row.Scan(
		&i.ID,
		&i.WorkflowID,
		&i.WorkflowVersion,
		&i.IdempotencyKey,
		&i.Status,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getExecutionByWorkflowAndIdempotencyKey = `-- name: GetExecutionByWorkflowAndIdempotencyKey :one
SELECT id, workflow_id, workflow_version, idempotency_key, status, started_at, completed_at, created_at, updated_at FROM executions
WHERE workflow_id = $1 AND idempotency_key = $2 LIMIT 1
`

type GetExecutionByWorkflowAndIdempotencyKeyParams struct {
	WorkflowID     pgtype.UUID
	IdempotencyKey string
}

func (q *Queries) GetExecutionByWorkflowAndIdempotencyKey(ctx context.Context, arg GetExecutionByWorkflowAndIdempotencyKeyParams) (Execution, error) {
	row := q.db.QueryRow(ctx, getExecutionByWorkflowAndIdempotencyKey, arg.WorkflowID, arg.IdempotencyKey)
	var i Execution
	err := row.Scan(
		&i.ID,
		&i.WorkflowID,
		&i.WorkflowVersion,
		&i.IdempotencyKey,
		&i.Status,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWebhookByPath = `-- name: GetWebhookByPath :one
SELECT id, workflow_id, path, secret, created_at FROM webhooks
WHERE path = $1 LIMIT 1
`

func (q *Queries) GetWebhookByPath(ctx context.Context, path string) (Webhook, error) {
	row := q.db.QueryRow(ctx, getWebhookByPath, path)
	var i Webhook
	err := row.Scan(
		&i.ID,
		&i.WorkflowID,
		&i.Path,
		&i.Secret,
		&i.CreatedAt,
	)
	return i, err
}

const getWorkflow = `-- name: GetWorkflow :one
SELECT id, name, created_at FROM workflows
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetWorkflow(ctx context.Context, id pgtype.UUID) (Workflow, error) {
	row := q.db.QueryRow(ctx, getWorkflow, id)
	var i Workflow
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const getWorkflowVersion = `-- name: GetWorkflowVersion :one
SELECT workflow_id, version, dag_definition, created_at FROM workflow_versions
WHERE workflow_id = $1 AND version = $2 LIMIT 1
`

type GetWorkflowVersionParams struct {
	WorkflowID pgtype.UUID
	Version    int32
}

func (q *Queries) GetWorkflowVersion(ctx context.Context, arg GetWorkflowVersionParams) (WorkflowVersion, error) {
	row := q.db.QueryRow(ctx, getWorkflowVersion, arg.WorkflowID, arg.Version)
	var i WorkflowVersion
	err := row.Scan(
		&i.WorkflowID,
		&i.Version,
		&i.DagDefinition,
		&i.CreatedAt,
	)
	return i, err
}

const getLatestWorkflowVersion = `-- name: GetLatestWorkflowVersion :one
SELECT workflow_id, version, dag_definition, created_at FROM workflow_versions
WHERE workflow_id = $1
ORDER BY version DESC LIMIT 1
`

func (q *Queries) GetLatestWorkflowVersion(ctx context.Context, workflowID pgtype.UUID) (WorkflowVersion, error) {
	row := q.db.QueryRow(ctx, getLatestWorkflowVersion, workflowID)
	var i WorkflowVersion
	err := row.Scan(
		&i.WorkflowID,
		&i.Version,
		&i.DagDefinition,
		&i.CreatedAt,
	)
	return i, err
}

const listExecutions = `-- name: ListExecutions :many
SELECT id, workflow_id, workflow_version, idempotency_key, status, started_at, completed_at, created_at, updated_at FROM executions
WHERE workflow_id = $1
AND ($3::timestamptz IS NULL OR created_at < $3)
ORDER BY created_at DESC
LIMIT $2
`

type ListExecutionsParams struct {
	WorkflowID pgtype.UUID
	Limit      int32
	Cursor     pgtype.Timestamptz
}

func (q *Queries) ListExecutions(ctx context.Context, arg ListExecutionsParams) ([]Execution, error) {
	rows, err := q.db.Query(ctx, listExecutions, arg.WorkflowID, arg.Limit, arg.Cursor)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Execution
	for rows.Next() {
		var i Execution
		if err := rows.Scan(
			&i.ID,
			&i.WorkflowID,
			&i.WorkflowVersion,
			&i.IdempotencyKey,
			&i.Status,
			&i.StartedAt,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateScheduleNextRun = `-- name: UpdateScheduleNextRun :exec
UPDATE schedules
SET next_run_at = $2, leased_by = NULL, lease_expires_at = NULL
WHERE id = $1
`

type UpdateScheduleNextRunParams struct {
	ID        pgtype.UUID
	NextRunAt pgtype.Timestamptz
}

func (q *Queries) UpdateScheduleNextRun(ctx context.Context, arg UpdateScheduleNextRunParams) error {
	_, err := q.db.Exec(ctx, updateScheduleNextRun, arg.ID, arg.NextRunAt)
	return err
}

const updateExecutionStatus = `-- name: UpdateExecutionStatus :exec
UPDATE executions
SET status = $2,
    updated_at = $3,
    completed_at = COALESCE($4, completed_at)
WHERE id = $1
`

type UpdateExecutionStatusParams struct {
	ID          pgtype.UUID
	Status      string
	UpdatedAt   pgtype.Timestamptz
	CompletedAt pgtype.Timestamptz
}

func (q *Queries) UpdateExecutionStatus(ctx context.Context, arg UpdateExecutionStatusParams) error {
	_, err := q.db.Exec(ctx, updateExecutionStatus,
		arg.ID,
		arg.Status,
		arg.UpdatedAt,
		arg.CompletedAt,
	)
	return err
}
